### ISSUE TITLE
TypeError: discord_js_1.Intents is not a constructor

### ISSUE THREAD

**Issue by ghost** [Androz2091/discord-logs#169]
**Promise:**
```
Promise {
  <rejected> TypeError: discord_js_1.Intents is not a constructor
      at /home/pi/Bots/Popcorn/node_modules/discord-logs/lib/index.js:47:19
      at step (/home/pi/Bots/Popcorn/node_modules/discord-logs/lib/index.js:33:23)
      at Object.next (/home/pi/Bots/Popcorn/node_modules/discord-logs/lib/index.js:14:53)
      at /home/pi/Bots/Popcorn/node_modules/discord-logs/lib/index.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (/home/pi/Bots/Popcorn/node_modules/discord-logs/lib/index.js:4:12)
      at module.exports (/home/pi/Bots/Popcorn/node_modules/discord-logs/lib/index.js:41:54)
      at Object.<anonymous> (/home/pi/Bots/Popcorn/Structures/index.js:17:1)
      at Module._compile (node:internal/modules/cjs/loader:1105:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
}
```

**Reason:**
```
TypeError: discord_js_1.Intents is not a constructor
    at /home/pi/Bots/Popcorn/node_modules/discord-logs/lib/index.js:47:19
    at step (/home/pi/Bots/Popcorn/node_modules/discord-logs/lib/index.js:33:23)
    at Object.next (/home/pi/Bots/Popcorn/node_modules/discord-logs/lib/index.js:14:53)
    at /home/pi/Bots/Popcorn/node_modules/discord-logs/lib/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/pi/Bots/Popcorn/node_modules/discord-logs/lib/index.js:4:12)
    at module.exports (/home/pi/Bots/Popcorn/node_modules/discord-logs/lib/index.js:41:54)
    at Object.<anonymous> (/home/pi/Bots/Popcorn/Structures/index.js:17:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
 ```

**Comment by SniperMoon** [comment]
Hi, this is because the "discord-logs" package is not yet compatible with V14 of discord.js

**Comment by zachjmurphy** [comment]
Okay. Thank you. Is there a plan to support v14 in the future?

**Comment by LWJerri** [comment]
Yeap, we need d.js v14 support.

**Comment by KingTeox** [comment]
#170

**Comment by NamVr** [comment]
No it isn't dead, it is maintained. I'll see if androz checks out this issue soon or I'll contribute myself

**Comment by KingTeox** [comment]
> No it isn't dead, it is maintained. I'll see if androz checks out this issue soon or I'll contribute myself

Any news ?

**Comment by NamVr** [comment]
@KingTeox I saw you already have made a pr, excellent!
