### ISSUE TITLE
Error on discord.js v14

### ISSUE THREAD

**Issue by MegalithOffical** [Androz2091/discord-logs#171]
In discord.js 14.3.0 (V14) Module gives that error

TypeError: discord_js_1.Intents is not a constructor
    at C:\Users\user\Desktop\v14-Altpayi-main\node_modules\discord-logs\lib\index.js:47:19
    at step (C:\Users\user\Desktop\v14-Altpayi-main\node_modules\discord-logs\lib\index.js:33:23)
    at Object.next (C:\Users\user\Desktop\v14-Altpayi-main\node_modules\discord-logs\lib\index.js:14:53)
    at C:\Users\user\Desktop\v14-Altpayi-main\node_modules\discord-logs\lib\index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\user\Desktop\v14-Altpayi-main\node_modules\discord-logs\lib\index.js:4:12)
    at module.exports (C:\Users\user\Desktop\v14-Altpayi-main\node_modules\discord-logs\lib\index.js:41:54)
    at Object.<anonymous> (C:\Users\user\Desktop\v14-Altpayi-main\main.js:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)

discord-logs version: ^2.0.1
Node.js version: 16.17.0

**Comment by lolollllo** [comment]
#170

**Comment by zachjmurphy** [comment]
I have published a v14 version of this project here that not only is v14 supported but also implements the pull requests #167 #156 #151: 

**GitHub Link:**
https://github.com/zachjmurphy/discord-logs

**NPM Package Link:**
https://www.npmjs.com/package/@zachjmurphy/discord-logs

**Comment by Androz2091** [comment]
Closed by #172
