### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cpojha** [Androz2091/discord-logs#27]
`/app/tests/test.js:9
    console.log("Ready. Logged as "+client.user.tag+" in "+client.guilds.cache.size+" servers.");
                                                                               ^
TypeError: Cannot read property 'size' of undefined
at Client.client.on (/app/tests/test.js:9:80)
    at Client.emit (events.js:194:15)
    at WebSocketConnection.triggerReady (/rbd/pnpm-volume/1ca3098b-affb-4b93-b7e8-fcd8a4a14bd0/node_modules/.registry.npmjs.org/discord.js/11.5.1/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:125:17)
    at WebSocketConnection.checkIfReady (/rbd/pnpm-volume/1ca3098b-affb-4b93-b7e8-fcd8a4a14bd0/node_modules/.registry.npmjs.org/discord.js/11.5.1/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:141:61)
    at GuildCreateHandler.handle (/rbd/pnpm-volume/1ca3098b-affb-4b93-b7e8-fcd8a4a14bd0/node_modules/.registry.npmjs.org/discord.js/11.5.1/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:13:31)
    at WebSocketPacketManager.handle (/rbd/pnpm-volume/1ca3098b-affb-4b93-b7e8-fcd8a4a14bd0/node_modules/.registry.npmjs.org/discord.js/11.5.1/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (/rbd/pnpm-volume/1ca3098b-affb-4b93-b7e8-fcd8a4a14bd0/node_modules/.registry.npmjs.org/discord.js/11.5.1/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/rbd/pnpm-volume/1ca3098b-affb-4b93-b7e8-fcd8a4a14bd0/node_modules/.registry.npmjs.org/discord.js/11.5.1/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/rbd/pnpm-volume/1ca3098b-affb-4b93-b7e8-fcd8a4a14bd0/node_modules/.registry.npmjs.org/ws/6.2.1/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:189:13)
` sir how to fix the.

**Comment by cpojha** [comment]
Please help me

**Comment by Androz2091** [comment]
Are you sure you're using discord.js v12? If you aren't, install it with `npm install discordjs/discord.js`

**Comment by cpojha** [comment]
Sir how to use it in a Discord channel or it will only shown in logs
