### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by anks095** [Androz2091/discord-logs#33]
Can't install it using ```npm i discord-logs``` , it's always giving error , even when I download the package through repo ,still can't install it . Please fix it ... error is like this :
```npm ERR! code ENOENT      
npm ERR! syscall spawn git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/discordjs/discord.js.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\anksark\AppData\Roaming\npm-cache\_logs\2020-04-16T11_13_21_994Z-debug.log```

and in the log file :

```verbose stack Error: spawn git ENOENT
20 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
20 verbose stack     at onErrorNT (internal/child_process.js:469:16)
20 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
21 verbose cwd C:\Users\anksark\Documents\WeirdTrexy
22 verbose Windows_NT 10.0.18363
23 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "./discord-logs"
24 verbose node v12.16.1
25 verbose npm  v6.13.4
26 error code ENOENT
27 error syscall spawn git
28 error path git
29 error errno ENOENT
30 error enoent Error while executing:
30 error enoent undefined ls-remote -h -t ssh://git@github.com/discordjs/discord.js.git
30 error enoent
30 error enoent
30 error enoent spawn git ENOENT
31 error enoent This is related to npm not being able to find a file.
32 verbose exit [ 1, true ]```

**Comment by anks095** [comment]
and my discord.js version is 12.1 and node version is 12.16.1....

**Comment by Androz2091** [comment]
* install git
* open git bash
* retry to install the package

**Comment by anks095** [comment]
it does not work.....at least it does not solve problem for me ....... note: i use visual studio code for editing.
is there no way i can install the package through npm like other packages? as i can install other packages just fine

**Comment by anks095** [comment]
nvr mind ..... did the installation in some other way ...which is totally unconventional ..... did not use git bash as it's crap

**Comment by Androz2091** [comment]
Hum... Did you just say that Git is crap in a **Git**hub issue? 😅 
I'm using MacOS and Linux but I think the Git bash is the only way to use git commands.
